name: 1.0.$(Rev:r)

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false


- task: kasunkodagoda.regex-match-replace.regex-match-replace.RegExMatchReplace@2
  displayName: 'Set Version'
  inputs:
    PathToFile: package.json
    RegEx: '"version": "1.0.0",'
    ValueToReplace: '"version": "$(Build.BuildNumber)",'


- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'


- task: Npm@1
  displayName: 'npm test'
  inputs:
    command: custom
    verbose: false
    customCommand: test


- task: Npm@1
  displayName: 'npm publish'
  inputs:
    command: publish
    verbose: true
    publishEndpoint: 'Public NPM Registry'

